group: travis_latest
language: node_js
node_js: node
cache: yarn
env:
  global:
  - secure: sV5RHhr6EtWOZZ8uyZ9SyPhUjiasNHMjbyrjoGCR/LMGHOz8SVqgG/b9yv6cpuRxsnq+MmbZIrrHlraLMHpYJ9sSFt/YDEGf7ggwYx8hE83/rph+hpJ5QqVECC/wjb7UISL3371BwAQXU8jaU8vYHcusYOLGDtwXhEW+QqJB+vEBBnM+VYPI+eqh84x6d1nNcAz2yr5kjeMsmt2xszWk4pLPYCoXppE1L7TW4f5thu13oX3N8pdvbMEdgjoyEEva4ECNvMKBsCoXgmmhmYWEP4zrbVt6pCzvN1Z8cksFDFzSFLwX2grABmRJz6EZis+eG6OSri/jQv1rgem2Z6O+I/SumWBOtJ73x6aglHfJnVpf7hRlvJ4mYKJ8FDgIip6RXHQMoksrQUmUIAIPEWfF8Vo668SEHk/752BedWPdXlGLKiADITdBm5aZI+q/UTsdMXmc8ghX1Ey8yni8PcWZvBbH1sr1nwoWVF0T8rJhd2gn9y1qHnDH3kLL+ak2xFNybBnAwJgSAY9fpzr5IGyDSLnozj1caB9oZcOd1k9PHzWeXvxWkPaHlyUcJ6l7RzzQUvF18Pl5VyE0nIA8GIGO+HkNd4OMaPS6bWi8FctN5BfdNCyGNO6a5+uXT3k5G+qY9eeA0fqgFEppCib08FY4gmQj2aYmwyGhLvga/Hm2hUU=
  - secure: X5ue2rKKu4NMPICHzo1X9FPVqAlnjSyaxjih2sOSUrma+dWsmkFRxINTMxSLujB62NDNo6hhHvRogD/sZMwSv3NJODmNtZOV85dOqjeMiMGsI0UUFOzQjTrLJydunyI8i+WIUEQMajXe7PXUsflExPkBZKnAZpmaml2tR5RMWnVGutQawG3QdCYjubwkR1G7C4OQVnfn44QMC6pEWrD4CBp1nX1uvVNwqI8MbZX0tQvkpmRPSWqfYD+owQkdcFdKrcwjMhZhgRec+P6A1ZngFt66VsQ8Wz1siskuqBS130otM8JjrMjXqmzY6RxUXIhLHn/dl3zYKrgOZTsvJnoupYahiUch6M2xTQhlpaxyxcOIRwRSeMnhb1bRErL53R9CH5IYhn2MCTPvjz23sXgqbEU9YCpVl4WeuAiSLpc2cUUFqol60llbJnoMseNurLhFy36MhZcYa+krP1Nlf69cOu7SWA+ZECcXaE1PWXIRjn5yNblLeqV+mOGsYVjBhgHiZ8cGE8s8GawVawlHVZhKHfDoeAfGEkcOhS0PjkGEZqTTC74u8oT1Uan5lV2vK64p6iUzG/O0gMHGaagqPJOxs9Zd1xjdo0qVjdZtGeW8KXIgBuufjQZU6M86Ikz5JZ+m85Z7D7D3pvmWFoVBh0tJU9f76URTfSADnjuGjAG5FI8=
branches:
  only:
    - master
deploy:
  provider: script
  skip_cleanup: true
  script:
  - yarn release
